/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import controlescasting.Fabrica;
import controlescasting.INegocio;
import java.util.AbstractList;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import objetosnegocio.Agente;
import objetosnegocio.Cliente;

/**
 *
 * @author miran
 */
public class FrmMenuCasting extends javax.swing.JFrame implements FrameBase {
    private INegocio negocio=Fabrica.fabricaN();
    private static FrmMenuCasting frmMenuCasting;
    private List<Agente>listaAgentes;
    private List<Cliente>listaClientes;
    /**
     * Creates new form FrmCasting
     */
    private FrmMenuCasting() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        this.listaAgentes= new ArrayList<>();
        this.listaClientes=new ArrayList<>();
    }

    public static FrmMenuCasting getFrmMenuCasting() {
        if (FrmMenuCasting.frmMenuCasting != null) {
            return frmMenuCasting;
        } else {
            FrmMenuCasting.frmMenuCasting = new FrmMenuCasting();
            return FrmMenuCasting.frmMenuCasting;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTittle = new javax.swing.JLabel();
        panAgentes = new javax.swing.JPanel();
        lbl = new javax.swing.JLabel();
        lblAgentes2 = new javax.swing.JLabel();
        panAgentes2 = new javax.swing.JPanel();
        lbl2 = new javax.swing.JLabel();
        lblRegistrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(41, 76, 125));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblTittle.setText(" Menú Castings ");
        lblTittle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 76, 125)));
        lblTittle.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        lblTittle.setForeground(new java.awt.Color(41, 76, 125));

        panAgentes.setBackground(new java.awt.Color(255, 255, 255));

        lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa96azul.png"))); // NOI18N
        lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMouseClicked(evt);
            }
        });

        lblAgentes2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        lblAgentes2.setForeground(new java.awt.Color(41, 76, 125));
        lblAgentes2.setText("Buscar Casting");
        lblAgentes2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAgentes2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panAgentesLayout = new javax.swing.GroupLayout(panAgentes);
        panAgentes.setLayout(panAgentesLayout);
        panAgentesLayout.setHorizontalGroup(
            panAgentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAgentesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAgentes2)
                .addGap(42, 42, 42))
            .addGroup(panAgentesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panAgentesLayout.setVerticalGroup(
            panAgentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAgentesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAgentes2))
        );

        panAgentes2.setBackground(new java.awt.Color(255, 255, 255));

        lbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registrar96azul.png"))); // NOI18N
        lbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl2MouseClicked(evt);
            }
        });

        lblRegistrar.setText(" Registrar Casting ");
        lblRegistrar.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        lblRegistrar.setForeground(new java.awt.Color(41, 76, 125));
        lblRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panAgentes2Layout = new javax.swing.GroupLayout(panAgentes2);
        panAgentes2.setLayout(panAgentes2Layout);
        panAgentes2Layout.setHorizontalGroup(
            panAgentes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAgentes2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        panAgentes2Layout.setVerticalGroup(
            panAgentes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAgentes2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRegistrar)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(lblTittle)
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panAgentes, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(panAgentes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTittle)
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panAgentes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panAgentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        FrmMenuPrincipal.getFrmMenuPrincipal().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMouseClicked
        FrmBuscarCasting.getFrmBuscarCasting().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblMouseClicked

    private void lbl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl2MouseClicked
        this.mostrarP_RegistroCastings();
    }//GEN-LAST:event_lbl2MouseClicked

    private void lblRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseClicked
       this.mostrarP_RegistroCastings();
    }//GEN-LAST:event_lblRegistrarMouseClicked

    private void lblAgentes2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgentes2MouseClicked
        FrmBuscarCasting.getFrmBuscarCasting().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblAgentes2MouseClicked
    
    private void mostrarP_RegistroCastings(){
        this.listaAgentes=new ArrayList<>();
        this.listaClientes=new ArrayList<>();
        this.buscarAgentes();
        this.buscarClientes();
        if(listaClientes.isEmpty()){
            this.mostrarMsj("No existe algún cliente registrado", 1);
            FrmRegistrarCliente.getFrmRegistrarCliente().setVisible(true);
            this.setVisible(false);
        }else if(listaAgentes.isEmpty()){
            this.mostrarMsj("No existe algún agente registrado", 1);
            FrmAgente.getFrmAgente().setVisible(true);
            this.setVisible(false);
        }else{
            FrmRegistrarCasting.getFrmRegistrarCasting().setListas(listaClientes, listaAgentes);
            FrmRegistrarCasting.getFrmRegistrarCasting().setVisible(true);
            this.setVisible(false);
        }
    }
    
    private void buscarAgentes(){
        this.listaAgentes = this.negocio.buscarAgentes();
    }
              
    private void buscarClientes(){
        this.listaClientes = this.negocio.buscarClientes();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lblAgentes2;
    private javax.swing.JLabel lblRegistrar;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JPanel panAgentes;
    private javax.swing.JPanel panAgentes2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mostrarMsj(String mensaje, int tipo) {
       if(tipo==0){
            JOptionPane.showMessageDialog(this, mensaje,
                        "Información", JOptionPane.INFORMATION_MESSAGE);
       }else if(tipo==1){
            JOptionPane.showMessageDialog(this, mensaje,
                        "Error", JOptionPane.ERROR_MESSAGE);
       }else{
           JOptionPane.showMessageDialog(this, mensaje,
                        "Advertencia", JOptionPane.WARNING_MESSAGE);
       }
    }
}
